### ISSUE TITLE
Bug in "searchthebucket"

### ISSUE THREAD

**Issue by casual1** [Flamezzz/FClueHunterEasy#14] opened 2015-09-05 17:56 UTC
Search the bucket in port sarim jail.

It went down to shantay pass and kept clicking the shantay guy for a minute.

**Comment by Flamezzz** [comment] 2015-09-05 20:21
Did it do anything of the dialogue? I've noticed it can sometimes take a while but never really fails.

Do you have a log?

**Comment by casual1** [comment] 2015-09-05 20:35
couldn't see because of the advert lol. saw the red cursor clicks on the guy though.. can't seem to reproduce it, I think this is the first time I faced this clue text in like 100 clues

if it was gonna start the dialogue, it's okay

**Comment by Flamezzz** [comment] 2015-09-05 20:39
Mhm... I'll try to reproduce it, thanks for reporting this issue :)

**Comment by Flamezzz** [comment] 2015-09-06 10:38
I was unable to reproduce this, closing it for now.

**Closed as completed by Flamezzz** 2015-09-06 10:38 UTC
Labels: bug

**Comment by casual1** [comment] 2015-09-13 19:08
I guess there's an additional chat line for those who didn't complete one of the desert quests, that the shantay notices a girl crying next to the pass and tells you. Will check next time I get there.
