### ISSUE TITLE
Loot counter error

### ISSUE THREAD

**Issue by casual1** [Flamezzz/FClueHunterEasy#9] opened 2015-09-04 01:57 UTC
The script has ran for a few hours, counting to 17M loot. To my horror, there was like 400K value of new rewards in the bank. It did not die, what happened?

**Comment by Flamezzz** [comment] 2015-09-04 10:16
Weird shit, just got a message someone got a 154k black pickaxe... It could be rsbuddy sometimes just returns wrong values :S

I'll have to output the entire reward table to see if that's the case.

It could of course also process the reward multiple times caused by major lag, perhaps this is the issue. But a 154k pickaxe would mean it did that 21 times lol

**Comment by casual1** [comment] 2015-09-04 10:48
the script stopped with rewards in the inventory, that's all I know

**Comment by casual1** [comment] 2015-09-05 23:19
just appeared on the list: Purple sweets (133K) :D three of them.

**Comment by Flamezzz** [comment] 2015-09-06 08:28
Did you get a log for me? I've never seen stuff like this lol

**Comment by Flamezzz** [comment] 2015-09-11 19:31
Most likely fixed in the next update, closing it for now.

**Closed as completed by Flamezzz** 2015-09-11 19:31 UTC
Labels: bug
